name: Docker Image CI

env:
  APP_PATH: apps/registration-api

on:
  push:
    branches: [ 'dev' ]
    paths:
      - ${{ APP_PATH }}
  pull_request:
    branches: [ 'dev' ]
    paths:
      - ${{ APP_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build registration api
      working-directory: ${{ APP_PATH }}
      run: |
        docker build -t test-device-reg-api .
        docker run -d -t test-device-reg-api

